### ISSUE TITLE
UIGestureRecognizer publisher

### ISSUE THREAD

**Issue by mattjgalloway** [freak4pc/CombineCocoa#6]
Have you considered adding a publisher for gesture recognisers? Would be neat.

I’m happy to have a look at adding myself, just wanted to raise the issue to track.

**Comment by freak4pc** [comment]
Hey @mattjgalloway! Would be happy to have it :) 

The only tricky part is that its not KVO-compliant, and also doesn't use UI Control Event. 

We'll have to make some custom publisher that sets the [target](https://developer.apple.com/documentation/uikit/uibarbuttonitem/1617154-target)	 and [action](https://developer.apple.com/documentation/uikit/uibarbuttonitem/1617154-target) on the UIBarButtonItem and exposes these as a Publisher.

**Comment by mattjgalloway** [comment]
Yep exactly. It’ll be different - just like in RxCocoa. That’s ok though - we can use the same paradigm for solving it.

**Comment by freak4pc** [comment]
@mattjgalloway Do you want to tackle it, or should I? :)

**Comment by mattjgalloway** [comment]
I can handle it sometime in the next month. If you want to get to it before then, then go for it! Happy to review anything.

**Comment by freak4pc** [comment]
Oh just realized you have two different threads :) I thought I'm replying to UIBarButtonItem ^_^ 

Anyways both sound like a good iea.

**Comment by freak4pc** [comment]
Solved in #8.
