### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by ppluskota** [freak4pc/CombineCocoa#91]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):
> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

**Comment by batkov** [comment]
@ppluskota but this lib is not in the list and is not using any of "privacy" capabilities. IMO it should not have any privacy manifest.
cc https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by ppluskota** [comment]
@batkov If I understand correctly each 3rd party library should have a privacy manifest. See the following URL for additional information https://developer.apple.com/news/?id=r1henawx
